[project]
name = "backend-flota"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.42.76",
    "cryptography>=46.0.7",
    "fastapi>=0.135.1",
    "minio>=7.2.20",
    "pydantic>=2.12.5",
    "pyjwt>=2.12.1",
    "pymysql>=1.1.2",
    "python-dateutil>=2.9.0.post0",
    "python-dotenv>=1.2.2",
    "requests>=2.33.1",
    "sqlalchemy>=2.0.48",
    "uvicorn[standard]>=0.41.0",
]
