from .get_files_node import get_files_node
from .document_classifier_node import document_classifier_node
from .dictamen_gas_analysis import dictamen_gas_analysis
from .circulation_card_analysis import circulation_card_analysis
from .insurance_pol_analysis import insurance_pol_analysis
from .armor_cert_analysis import armor_cert_analysis
from .bill_analysis import bill_analysis